services:
  web:
    build: .
    container_name: web
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-www:/usr/share/nginx/html
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'certbot certonly --webroot --webroot-path=/usr/share/nginx/html --email rob@spotplotter.com --agree-tos --no-eff-email --staging -d spotplotter.com && certbot renew --dry-run'"

volumes:
  certbot-etc:
  certbot-var:
  nginx-www:
