version: "3.8"

services:
  web:
    build: .
    container_name: spotplot-react
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - nginx-www:/usr/share/nginx/html
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: >
      /bin/sh -c "
      certbot certonly --webroot --webroot-path=/usr/share/nginx/html
      --email rob@spotplotter.com --agree-tos --no-eff-email
      --staging -d spotplotter.com -d www.spotplotter.com &&
      certbot renew --dry-run"

volumes:
  certbot-etc:
  certbot-var:
  nginx-www:
