name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: web

jobs:
  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Git Version
        id: version
        run: echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            .

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.VERSION }} $IMAGE_ID:${{ env.VERSION }}
          docker push $IMAGE_ID:${{ env.VERSION }}
          echo "pushed $IMAGE_ID:${{ env.VERSION }}"
